CREATE TABLE `data_platform_delivery_document_header_data`
(
    `DeliveryDocument`               int(16) NOT NULL,
    `OrderID`                        int(16) DEFAULT NULL,
    `OrderType`                      varchar(3) DEFAULT NULL,
    `Buyer`                          int(12) DEFAULT NULL,
    `Seller`                         int(12) DEFAULT NULL,
    `ContractType`                   varchar(4) DEFAULT NULL,
    `OrderValidityStartDate`         date DEFAULT NULL,
    `OrderValidityEndDate`           date DEFAULT NULL,
    `InvoiceScheduleStartDate`       date DEFAULT NULL,
    `InvoiceScheduleEndDate`         date DEFAULT NULL,
    `IssuingLocationTimeZone`        varchar(3) DEFAULT NULL,
    `ReceivingLocationTimeZone`      varchar(3) DEFAULT NULL,
    `DocumentDate`                   date DEFAULT NULL,
    `PlannedGoodsIssueDate`          date DEFAULT NULL,
    `PlannedGoodsIssueTime`          time DEFAULT NULL,
    `PlannedGoodsReceiptDate`        date DEFAULT NULL,
    `PlannedGoodsReceiptTime`        time DEFAULT NULL,
    `BillingDocumentDate`            date DEFAULT NULL,
    `CompleteDeliveryIsDefined`      tinyint(1) DEFAULT NULL,
    `OverallDeliveryStatus`          varchar(2) DEFAULT NULL,
    `CreationDate`                   date DEFAULT NULL,
    `CreationTime`                   time DEFAULT NULL,
    `IssuingBlockReason`             tinyint(1) DEFAULT NULL,
    `ReceivingBlockReason`           tinyint(1) DEFAULT NULL,
--  `DeliveryDocumentBySupplier`     varchar(35) DEFAULT NULL,
    `GoodsIssueOrReceiptSlipNumber`  varchar(35) DEFAULT NULL,
    `HeaderBillgIncompletionStatus`  varchar(1) DEFAULT NULL,
    `HeaderBillingBlockReason`       tinyint(1) DEFAULT NULL,
    `HeaderGrossWeight`              float(13) DEFAULT NULL,
    `HeaderNetWeight`                float(13) DEFAULT NULL,
    `HeaderWeightUnit`               varchar(3) DEFAULT NULL,
    `Incoterms`                      varchar(3) DEFAULT NULL,
    `IsExportImportDelivery`         tinyint(1) DEFAULT NULL,
    `LastChangeDate`                 date DEFAULT NULL,
    `IssuingPlantBusinessPartner`    varchar(4) DEFAULT NULL,
    `IssuingPlant`                   varchar(4) DEFAULT NULL,
    `ReceivingPlantBusinessPartner`  varchar(4) DEFAULT NULL,
    `ReceivingPlant`                 varchar(4) DEFAULT NULL,
    `DeliverToParty`                 int(12) DEFAULT NULL,
    `DeliverFromParty`               int(12) DEFAULT NULL,
    `DeliverToPartyLanguage`         varchar(2) DEFAULT NULL,
    `DeliverFromPartyLanguage`       varchar(2) DEFAULT NULL,
    `TransactionCurrency`            varchar(5) DEFAULT NULL,
    `OverallDelivReltdBillgStatus`   varchar(2) DEFAULT NULL,
    
    PRIMARY KEY (`DeliveryDocument`),
    
    CONSTRAINT `DataPlatformDeliveryDocumentHeaderDataOrderID_fk` FOREIGN KEY (`OrderID`, `OrderType`, `ContractType`, `OrderValidityStartDate`, `OrderValidityEndDate`, `InvoiceScheduleStartDate`, `InvoiceScheduleEndDate`, `TransactionCurrency`) REFERENCES `data_platform_orders_header_data` (`OrderID`, `OrderType`, `ContractType`, `ValidityStartDate`, `ValidityEndDate`, `InvoiceScheduleStartDate`, `InvoiceScheduleEndDate`, `TransactionCurrency`),
    CONSTRAINT `DataPlatformDeliveryDocumentHeaderDataIncoterms_fk` FOREIGN KEY (`Incoterms`) REFERENCES `data_platform_incoterms_incoterms_data` (`Incoterms`),
    CONSTRAINT `DataPlatformDeliveryDocumentHeaderDataIssuingPlant_fk` FOREIGN KEY (`IssuingPlantBusinessPartner`, `IssuingPlant`) REFERENCES `data_platform_plant_general_data` (`BusinessPartner`, `Plant`),
    CONSTRAINT `DataPlatformDeliveryDocumentHeaderDataReceivingPlant_fk` FOREIGN KEY (`ReceivingPlantBusinessPartner`, `ReceivingPlant`) REFERENCES `data_platform_plant_general_data` (`BusinessPartner`, `Plant`),
    CONSTRAINT `DataPlatformDeliveryDocumentHeaderDataDeliverToParty_fk` FOREIGN KEY (`DeliverToParty`, `DeliverFromParty`) REFERENCES `data_platform_orders_header_partner_data` (`BusinessPartner`, `BusinessPartner`),
    CONSTRAINT `DataPlatformDeliveryDocumentHeaderDataDeliverToPartyLanguage_fk` FOREIGN KEY (`DeliverToPartyLanguage`, `DeliverFromPartyLanguage`) REFERENCES `data_platform_business_partner_general_data` (`Language`, `Language`),

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
